### ISSUE TITLE
API keys storage

### ISSUE THREAD

**Issue by JettChenT** [JettChenT/scan-for-webcams#13]
Up until now, scan-for-webcams has been using environs to store API keys, while recently I've found an alternative [here](https://github.com/theskumar/python-dotenv), where users write their api keys into the .env file, so that they don't have to set the environ everytime they run the app.

Which one should we use?

**Comment by henrytriplette** [comment]
Under Windows I've used [Python decouple](https://able.bio/rhett/how-to-set-and-get-environment-variables-in-python--274rgt5#:~:text=To%20set%20and%20get%20environment%20variables%20in%20Python%20you%20can,Get%20environment%20variables%20USER%20%3D%20os.), it requires only 3 edits to the code in search.py:

Add
`from decouple import config`

Search and replace `os.environ.get` with `config`

Done!

**Comment by JettChenT** [comment]
> Under Windows I've used [Python decouple](https://able.bio/rhett/how-to-set-and-get-environment-variables-in-python--274rgt5#:~:text=To%20set%20and%20get%20environment%20variables%20in%20Python%20you%20can,Get%20environment%20variables%20USER%20%3D%20os.), it requires only 3 edits to the code in search.py:
> 
> Add
> `from decouple import config`
> 
> Search and replace `os.environ.get` with `config`
> 
> Done!

Thanks for the suggestion!
