### ISSUE TITLE
Clarifai API key error

### ISSUE THREAD

**Issue by louraider** [JettChenT/scan-for-webcams#32]
Hi. After add envs and start main.py have this error, cant do with that anything. Is this my fault ?
have file CLARIFAI_API_KEY.env with export "CLARIFAI_API_KEY"="<AP_ KEY_HERE>"
Thank you.

clarifai.errors.ApiError: b'GET https://api.clarifai.com/v2/models FAILED(1605376096.0716262). status_code: 401, reason: Unauthorized, error_code: 11008, error_description: Invalid API key or Invalid API key/application pair, error_details: Invalid format of key.\n >> Python client 2.6.2 with Python 3.9.0 on win32\n >> GET https://api.clarifai.com/v2/models\n >> REQUEST(1605376096.0716262) {\n  "page": 1,\n  "per_page": 20\n}\n >> RESPONSE(1605376096.0716262) {\n  "status": {\n    "code": 11008,\n    "description": "Invalid API key or Invalid API key/application pair",\n    "details": "Invalid format of key.",\n    "req_id": "49d1691503f941b8ade82f5863d56387"\n  },\n  "models": []\n}'

**Comment by JettChenT** [comment]
Did you execute the command "source CLARIFAI_API_KEY.env" before running the program?

**Comment by louraider** [comment]
> Did you execute the command "source CLARIFAI_API_KEY.env" before running the program?

Yes

**Comment by JettChenT** [comment]
This might be some problems with your api key in environ. The program must have detected the api key in environ, because it will raise a keyerror if it didn't.
<img width="405" alt="Screen Shot 2020-11-22 at 8 10 34 PM" src="https://user-images.githubusercontent.com/45888395/99903352-c8f8dc80-2cfe-11eb-8044-48a1ee1b5f71.png">

**Comment by louraider** [comment]
> This might be some problems with your api key in environ. The program must have detected the api key in environ, because it will raise a keyerror if it didn't.
> <img alt="Screen Shot 2020-11-22 at 8 10 34 PM" width="405" src="https://user-images.githubusercontent.com/45888395/99903352-c8f8dc80-2cfe-11eb-8044-48a1ee1b5f71.png">

I unerstand, so i deleted app and create new, and it doesn't help. ok thank you for help, i keep trying.

**Comment by JettChenT** [comment]
Can you print the environ value of the clarifai API key?
