### ISSUE TITLE
wont work for webcamxp

### ISSUE THREAD

**Issue by xxdreck** [JettChenT/scan-for-webcams#61]
it says every time "get data from API failed"

**Comment by JettChenT** [comment]
Hello, I've added debug mode to this application. Please update the software with pip, and run this:
`sfw search webcamXP --debug=True`
And please send the bug you've encountered here, thanks!

**Comment by JettChenT** [comment]
This issue is closed due to inactivity

**Comment by randomfrog13** [comment]
Now it says
× Get data from API failed
ERROR:
<class 'shodan.exception.APIError'>
