### ISSUE TITLE
webcamxp not working 

### ISSUE THREAD

**Issue by absurdcode0** [JettChenT/scan-for-webcams#69]
sfw search webcamXP
× Get data from API failed

sfw search webcamXP --debug=True
× Get data from API failed
ERROR:
<class 'shodan.exception.APIError'>

**Comment by JettChenT** [comment]
Hello, sorry for not working on this project for a long time. I've updated this repo with grpc support and  switched to a new 
 installation method(similar to [sherlock](https://github.com/sherlock-project/sherlock)). 

First, please reinstall this project with the new method( see the new README )

On my local machine, searching for webcamXP currently works. Nevertheless, try switching on `--debug=True` again and see what happens(in the current version I've add more traceback for bug tracking.)

**Comment by JettChenT** [comment]
Hello~ My Shodan search query for webcamXP is `product:webcamXP`.
I'm working on supporting webcamXP for free accounts. For a quick fix, edit `cams.json` and change `search_q` in `sfw/cams.json` to `webcamXP`

**Comment by JettChenT** [comment]
Closed due to inactivity.
