### ISSUE TITLE
Clarifai 

### ISSUE THREAD

**Issue by orangelime1** [JettChenT/scan-for-webcams#95]
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/clarifai/rest/client.py", line 1088, in init_model_cache
    model_type = m.output_info['type']
KeyError: 'type'

You are using the deprecated Python REST package. Please replace your code with the new & updated Python gRPC client: https://github.com/Clarifai/clarifai-python-grpc

**Comment by JettChenT** [comment]
Hello, sorry for not working on this project for a long time. I've updated this repo with grpc support and  switched to a new installation method(similar to [sherlock](https://github.com/sherlock-project/sherlock)). 

Installing this project again(see the new README) should solve your problem!
